Repository Uni-class/catch-up-repo, pull requests merged in 2024-07, with the labels that each got.

#8 Fe 6 reactqueryconfig
  packages/front-end/.eslintrc.json
  packages/front-end/app/globals.css
  packages/front-end/app/layout.tsx
  packages/front-end/package.json
  packages/front-end/util/query-client-provider.tsx
Labels: enhancement

#12 Be 7 backend develop init
  .gitignore
  packages/api-server/.prettierrc
  packages/api-server/package.json
  packages/api-server/src/app.controller.ts
  packages/api-server/src/app.module.ts
  packages/api-server/src/configs/typeorm.config.ts
  packages/api-server/src/main.ts
  packages/api-server/webpack-hmr.config.js
  packages/api-server/webpack.config.js
  yarn.lock
Labels: enhancement

#16 Be dev
  .gitignore
  packages/api-server/.prettierrc
  packages/api-server/package.json
  packages/api-server/src/app.controller.ts
  packages/api-server/src/app.module.ts
  packages/api-server/src/configs/typeorm.config.ts
  packages/api-server/src/main.ts
  packages/api-server/webpack-hmr.config.js
  packages/api-server/webpack.config.js
  packages/front-end/.eslintrc.json
  packages/front-end/.gitignore
  packages/front-end/.storybook/main.ts
  packages/front-end/.storybook/preview.tsx
  packages/front-end/app/globals.css
  packages/front-end/app/layout.tsx
  packages/front-end/app/login/page.tsx
  packages/front-end/app/page.tsx
  packages/front-end/next.config.mjs
  packages/front-end/package.json
  packages/front-end/provider/index.tsx
  packages/front-end/provider/jotai-provider.tsx
  packages/front-end/provider/query-client-provider.tsx
  packages/front-end/provider/style-provider.tsx
  packages/front-end/provider/styled-components-provider.tsx
  packages/front-end/public/icon/naver-icon.png
  packages/front-end/stories/Button.stories.ts
  packages/front-end/stories/Button.tsx
  packages/front-end/stories/Configure.mdx
  packages/front-end/stories/Header.stories.ts
  packages/front-end/stories/Header.tsx
  packages/front-end/stories/Page.stories.ts
  packages/front-end/stories/Page.tsx
  packages/front-end/stories/assets/accessibility.png
  packages/front-end/stories/assets/accessibility.svg
  packages/front-end/stories/assets/addon-library.png
  packages/front-end/stories/assets/assets.png
  packages/front-end/stories/assets/avif-test-image.avif
  packages/front-end/stories/assets/context.png
  packages/front-end/stories/assets/discord.svg
  packages/front-end/stories/assets/docs.png
  packages/front-end/stories/assets/figma-plugin.png
  packages/front-end/stories/assets/github.svg
  packages/front-end/stories/assets/share.png
  packages/front-end/stories/assets/styling.png
  packages/front-end/stories/assets/testing.png
  packages/front-end/stories/assets/theming.png
  packages/front-end/stories/assets/tutorials.svg
  packages/front-end/stories/assets/youtube.svg
  packages/front-end/stories/button.css
  packages/front-end/stories/header.css
  packages/front-end/stories/page.css
  packages/front-end/style/theme.ts
Labels: enhancement

#25 Be dev - naver login test
  packages/api-server/package.json
  packages/api-server/src/app.module.ts
  packages/api-server/src/auth/auth.controller.spec.ts
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/auth.module.ts
  packages/api-server/src/auth/auth.service.spec.ts
  packages/api-server/src/auth/auth.service.ts
  packages/api-server/src/auth/guards/naverauth.guard.ts
  packages/api-server/src/auth/strateties/naver.strategy.ts
  packages/api-server/src/users/dto/create-user.dto.ts
  packages/api-server/src/users/dto/update-user.dto.ts
  packages/api-server/src/users/entities/user.entity.ts
  packages/api-server/src/users/users.controller.spec.ts
  packages/api-server/src/users/users.controller.ts
  packages/api-server/src/users/users.module.ts
  packages/api-server/src/users/users.service.spec.ts
  packages/api-server/src/users/users.service.ts
  yarn.lock
Labels: enhancement

#33 Be 14 oauth develop - kakao, google 추가
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/auth.service.ts
  packages/api-server/src/auth/guards/googleauth.guard.ts
  packages/api-server/src/auth/guards/kakaoauth.guard.ts
  packages/api-server/src/auth/strateties/google.strategy.ts
  packages/api-server/src/auth/strateties/kakao.strategy.ts
Labels: enhancement

#37 Be dev - kakao, google auth test add
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/auth.service.ts
  packages/api-server/src/auth/guards/googleauth.guard.ts
  packages/api-server/src/auth/guards/kakaoauth.guard.ts
  packages/api-server/src/auth/strateties/google.strategy.ts
  packages/api-server/src/auth/strateties/kakao.strategy.ts
Labels: enhancement

#39 fix: kakao login
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/auth.module.ts
  packages/api-server/src/auth/strateties/kakao.strategy.ts
  packages/front-end/app/login/_components/kakao-login.tsx
Labels: bug

#46 Migration 43 pandacss
  packages/front-end/.gitignore
  packages/front-end/app/globals.css
  packages/front-end/app/layout.tsx
  packages/front-end/app/login/_components/naver-login.tsx
  packages/front-end/next.config.mjs
  packages/front-end/package.json
  packages/front-end/panda.config.ts
  packages/front-end/postcss.config.cjs
  packages/front-end/postcss.config.mjs
  packages/front-end/provider/index.tsx
  packages/front-end/provider/style-provider.tsx
  packages/front-end/provider/styled-components-provider.tsx
  packages/front-end/stories/Button.tsx
  packages/front-end/style/theme.ts
  packages/front-end/tailwind.config.ts
  yarn.lock
Labels: enhancement

#53 refactor: OAuth2 Login Button
  .idea/.gitignore
  .idea/catch-up-repo.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  packages/front-end/app/login/_components/login-button.tsx
  packages/front-end/app/login/_const/ProviderData.ts
  packages/front-end/app/login/_style/login-button-container.tsx
  packages/front-end/app/login/_type/OAuth2DataType.ts
  packages/front-end/app/login/_type/ProviderEnum.ts
  packages/front-end/app/login/page.tsx
Labels: enhancement

#51 Be: oauth login user data to db && Make JWT
  packages/api-server/package.json
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/auth.module.ts
  packages/api-server/src/auth/auth.service.ts
  packages/api-server/src/auth/guards/jwt.guard.ts
  packages/api-server/src/auth/guards/refresh.guard.ts
  packages/api-server/src/auth/jwt.payload.ts
  packages/api-server/src/auth/strateties/google.strategy.ts
  packages/api-server/src/auth/strateties/jwt.strategy.ts
  packages/api-server/src/auth/strateties/kakao.strategy.ts
  packages/api-server/src/auth/strateties/naver.strategy.ts
  packages/api-server/src/auth/strateties/refresh.strategy.ts
  packages/api-server/src/main.ts
  packages/api-server/src/users/dto/create-user.dto.ts
  packages/api-server/src/users/entities/user.entity.ts
  packages/api-server/src/users/user.converter.ts
  packages/api-server/src/users/users.controller.ts
  packages/api-server/src/users/users.module.ts
  packages/api-server/src/users/users.service.ts
  yarn.lock
Labels: enhancement

#57 refactor: Login Page Design
  packages/front-end/Config.ts
  packages/front-end/app/login/_components/login-button.tsx
  packages/front-end/app/login/_style/login-button-container.tsx
  packages/front-end/app/login/page.tsx
  packages/front-end/panda.config.ts
  packages/front-end/style/global-css.ts
  packages/front-end/style/theme.ts
Labels: enhancement

#61 Fix api server db connect and strategy
  packages/api-server/package.json
  packages/api-server/src/app.module.ts
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/auth.module.ts
  packages/api-server/src/auth/auth.service.ts
  packages/api-server/src/auth/strateties/google.strategy.ts
  packages/api-server/src/auth/strateties/jwt.strategy.ts
  packages/api-server/src/auth/strateties/kakao.strategy.ts
  packages/api-server/src/auth/strateties/naver.strategy.ts
  packages/api-server/src/auth/strateties/refresh.strategy.ts
  packages/api-server/src/configs/typeorm.config.ts
  packages/api-server/src/users/entities/user.entity.ts
  packages/api-server/src/users/user.converter.ts
  packages/api-server/src/users/users.service.ts
  packages/api-server/tsconfig.json
  yarn.lock
Labels: bug

#71 Be/69 exception andresponse
  packages/api-server/src/exception/all-exception.filter.ts
  packages/api-server/src/interceptor/response.interceptor.ts
  packages/api-server/src/main.ts
Labels: enhancement

#74 Change Component Naming Convention
  packages/front-end/app/login/_components/LoginButton.tsx
  packages/front-end/app/login/_style/LoginButtonContainer.tsx
  packages/front-end/app/login/page.tsx
  packages/front-end/components/Divider.tsx
  packages/front-end/components/Switch.tsx
  packages/front-end/stories/divider.stories.tsx
  packages/front-end/stories/switch.stories.tsx
Labels: enhancement

#75 Be/72 fix create user dto
  packages/api-server/src/users/dto/create-user.dto.ts
  packages/api-server/src/users/dto/update-user.dto.ts
Labels: enhancement

#79 Fix user dto
  packages/api-server/src/users/dto/create-user.dto.ts
  packages/api-server/src/users/dto/update-user.dto.ts
Labels: bug

#80 Fix response interceptor and auth controller
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/interceptor/response.interceptor.ts
Labels: bug

#85 feat: Create LineEdit Component
  packages/front-end/app/dashboard/page.tsx
  packages/front-end/app/login/page.tsx
  packages/front-end/components/LineEdit.tsx
Labels: development

#90 feat: Create Button Component
  packages/front-end/app/dashboard/page.tsx
  packages/front-end/app/login/_components/LoginButton.tsx
  packages/front-end/components/Button.tsx
  packages/front-end/components/LineEdit.tsx
Labels: development

#95 92 userouter
  packages/front-end/app/dashboard/_components/Sidebar/SidebarMenu.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarUserSwitch.tsx
  packages/front-end/app/login/page.tsx
  packages/front-end/hook/useRouter.tsx
Labels: enhancement, development

#96 Be/93 user crud
  packages/api-server/src/auth/auth.module.ts
  packages/api-server/src/auth/strateties/jwt.strategy.ts
  packages/api-server/src/auth/strateties/refresh.strategy.ts
  packages/api-server/src/exception/all-exception.filter.ts
  packages/api-server/src/main.ts
  packages/api-server/src/users/decorators/user-id.decorator.ts
  packages/api-server/src/users/entities/user.entity.ts
  packages/api-server/src/users/users.controller.ts
  packages/api-server/src/users/users.service.ts
Labels: bug, development

#100 94 improve switch sidebar design
  packages/front-end/app/dashboard/_components/Sidebar/SidebarMenu.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarMenuGroup.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarUser.tsx
  packages/front-end/app/dashboard/_components/Sidebar/index.tsx
  packages/front-end/components/Button.tsx
  packages/front-end/components/Divider.tsx
  packages/front-end/components/LineEdit.tsx
  packages/front-end/components/Switch.tsx
  packages/front-end/public/icon/logo.png
Labels: enhancement

#107 fix: Fix User Entity
  packages/api-server/src/users/entities/user.entity.ts
Labels: fix

#116 Be/114 auth to bearer
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/strateties/jwt.strategy.ts
  packages/api-server/src/auth/strateties/refresh.strategy.ts
  packages/api-server/src/files/files.controller.ts
  packages/api-server/src/main.ts
  packages/api-server/src/notes/notes.controller.ts
  packages/api-server/src/sessions/sessions.controller.ts
  packages/api-server/src/users/users.controller.ts
Labels: enhancement

#112 init: File Controller / Service
  packages/api-server/src/files/files.controller.ts
  packages/api-server/src/files/files.service.ts
  packages/front-end/app/dashboard/_components/Sidebar/SidebarMenu.tsx
Labels: development

#102 98 table
  packages/front-end/app/dashboard/_components/Sidebar/SidebarMenu.tsx
  packages/front-end/app/login/page.tsx
  packages/front-end/components/Table.tsx
  packages/front-end/stories/Table.stories.tsx
Labels: enhancement, development

#118 117 session api exception handling
  packages/api-server/src/sessions/sessions.controller.ts
  packages/api-server/src/sessions/sessions.service.ts
Labels: development

#121 feat: Append Cors origin
  packages/api-server/src/main.ts
Labels: enhancement

#124 Be/122 url update
  packages/api-server/src/files/files.controller.ts
  packages/api-server/src/sessions/sessions.controller.ts
  packages/api-server/src/users/types/user-session-body.type.ts
  packages/api-server/src/users/types/user-session-query.type.ts
  packages/api-server/src/users/users.controller.ts
Labels: enhancement, fix

#128 fix: import problem
  packages/api-server/src/files/files.controller.ts
  packages/api-server/src/sessions/sessions.controller.ts
Labels: fix

#130 108 api scenario
  packages/front-end/app/dashboard/(data)/session/_components/SessionTable.tsx
  packages/front-end/app/dashboard/(data)/session/page.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarMenu.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarUserSwitch.tsx
  packages/front-end/hook/useCheckBoxes.tsx
  packages/front-end/mocks/browser.ts
  packages/front-end/mocks/data/sessions.ts
  packages/front-end/mocks/handlers.ts
  packages/front-end/mocks/handlers/user.ts
  packages/front-end/package.json
  packages/front-end/provider/msw-provider.tsx
  packages/front-end/provider/query-client-provider.tsx
  packages/front-end/stories/Table.stories.tsx
  packages/front-end/tsconfig.json
  packages/front-end/util/axios.ts
  yarn.lock
Labels: bug

#129 125 move exception handlers
  packages/api-server/src/files/files.controller.ts
  packages/api-server/src/files/files.service.ts
  packages/api-server/src/sessions/sessions.controller.ts
  packages/api-server/src/sessions/sessions.module.ts
  packages/api-server/src/sessions/sessions.service.ts
Labels: enhancement

#134 Be/127 aws s3 setting
  packages/api-server/package.json
  packages/api-server/src/files/dto/create-file.dto.ts
  packages/api-server/src/files/dto/file-upload.response.dto.ts
  packages/api-server/src/files/entities/file.entity.ts
  packages/api-server/src/files/files.controller.ts
  packages/api-server/src/files/files.service.ts
  packages/api-server/src/users/entities/user.entity.ts
  yarn.lock
Labels: development

#143 fix: files.service
  packages/api-server/src/files/files.service.ts
Labels: fix

#145 feat: Create Button LineEdit Storybook
  packages/front-end/stories/Button.stories.tsx
  packages/front-end/stories/LineEdit.stories.tsx
Labels: development

#148 refactor: Login Redirect Url change
  packages/api-server/src/auth/auth.controller.ts
Labels: enhancement

#147 138 modal container
  packages/front-end/app/dashboard/(data)/session/_components/SessionTable.tsx
  packages/front-end/app/dashboard/@modal/default.tsx
  packages/front-end/app/dashboard/@modal/user-menu/page.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarUser.tsx
  packages/front-end/app/dashboard/layout.tsx
  packages/front-end/components/ModalContainer.tsx
  packages/front-end/mocks/handlers.ts
  packages/front-end/stories/switch.stories.tsx
Labels: development

#152 Be/151 user sessions api
  packages/api-server/src/user-sessions/entities/user-session.entity.ts
  packages/api-server/src/users/users.controller.ts
  packages/api-server/src/users/users.service.ts
  packages/front-end/schema/backend.schema.ts
Labels: bug, enhancement, fix

#150 refactor: Storybook
  packages/front-end/components/Button.tsx
  packages/front-end/components/Divider.tsx
  packages/front-end/components/LineEdit.tsx
  packages/front-end/components/Switch.tsx
  packages/front-end/components/Table.tsx
  packages/front-end/components/Text.tsx
  packages/front-end/stories/Button.stories.tsx
  packages/front-end/stories/Divider.stories.tsx
  packages/front-end/stories/Heading.stories.tsx
  packages/front-end/stories/LineEdit.stories.tsx
  packages/front-end/stories/Paragraph.stories.tsx
  packages/front-end/stories/Switch.stories.tsx
  packages/front-end/stories/Table.stories.tsx
Labels: enhancement

#157 156 user info modal
  packages/front-end/app/dashboard/(data)/session/_components/SessionTable.tsx
  packages/front-end/app/dashboard/@modal/user-menu/_components/UserInfoEdit.tsx
  packages/front-end/app/dashboard/@modal/user-menu/_components/UserModal.tsx
  packages/front-end/app/dashboard/@modal/user-menu/_components/UserModalTop.tsx
  packages/front-end/app/dashboard/@modal/user-menu/page.tsx
  packages/front-end/mocks/handlers.ts
Labels: development

#161 155 refresh strategy
  packages/api-server/src/auth/auth.module.ts
  packages/api-server/src/auth/strateties/refresh.strategy.ts
  packages/front-end/app/dashboard/(data)/session/_components/SessionTable.tsx
  packages/front-end/app/dashboard/@modal/user-menu/_components/UserInfoEdit.tsx
  packages/front-end/app/dashboard/@modal/user-menu/_components/UserModal.tsx
  packages/front-end/package.json
Labels: bug

#166 refactor: Change response of /user/sessions
  packages/api-server/src/users/users.controller.ts
  packages/api-server/src/users/users.service.ts
Labels: fix

#171 Be/170 auth logout
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/auth.module.ts
  packages/api-server/src/auth/auth.service.ts
  packages/api-server/src/users/users.service.ts
Labels: enhancement, development, fix

#169 Be/168 file fileid
  packages/api-server/src/files/dto/update-file.dto.ts
  packages/api-server/src/files/files.controller.ts
  packages/api-server/src/files/files.service.ts
  packages/api-server/src/users/users.controller.ts
Labels: enhancement, development

#173 154 refactor sidebar
  packages/front-end/app/dashboard/(data)/session/host/_components/SessionHeader.tsx
  packages/front-end/app/dashboard/(data)/session/host/_components/SessionTable.tsx
  packages/front-end/app/dashboard/(data)/session/host/page.tsx
  packages/front-end/app/dashboard/(data)/session/participant/_components/SessionHeader.tsx
  packages/front-end/app/dashboard/(data)/session/participant/_components/SessionTable.tsx
  packages/front-end/app/dashboard/(data)/session/participant/page.tsx
  packages/front-end/app/dashboard/@modal/default.tsx
  packages/front-end/app/dashboard/@modal/user-menu/page.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarBaseElement.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarDirectory.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarGroup.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarLink.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarMenu.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarMenuGroup.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarUser.tsx
  packages/front-end/app/dashboard/_components/Sidebar/SidebarUserSwitch.tsx
  packages/front-end/app/dashboard/_components/Sidebar/index.tsx
  packages/front-end/app/dashboard/page.tsx
  packages/front-end/app/settings/_components/UserInfoEdit.tsx
  packages/front-end/app/settings/_components/UserModal.tsx
  packages/front-end/app/settings/_components/UserModalTop.tsx
  packages/front-end/app/settings/page.tsx
  packages/front-end/next.config.mjs
  packages/front-end/package.json
  packages/front-end/provider/OverlayProvider.tsx
  packages/front-end/provider/index.tsx
  packages/front-end/public/icons/cast.svg
  packages/front-end/public/icons/chevron-down.svg
  packages/front-end/public/icons/chevron-up.svg
  packages/front-end/public/icons/database.svg
  packages/front-end/public/icons/external-link.svg
  packages/front-end/public/icons/layout.svg
  packages/front-end/public/icons/log-out.svg
  packages/front-end/public/icons/plus-circle.svg
  packages/front-end/public/icons/settings.svg
  yarn.lock
Labels: enhancement

#177 167 session detail
  packages/front-end/app/dashboard/(data)/session/host/_components/SessionTable.tsx
  packages/front-end/app/dashboard/(data)/session/host/page.tsx
  packages/front-end/app/dashboard/(data)/session/participant/_components/SessionTable.tsx
  packages/front-end/app/dashboard/(data)/session/participant/page.tsx
  packages/front-end/app/sessions/[sessionId]/detail/_components/HostSession/index.tsx
  packages/front-end/app/sessions/[sessionId]/detail/_components/ParticipantSession/index.tsx
  packages/front-end/app/sessions/[sessionId]/detail/error.tsx
  packages/front-end/app/sessions/[sessionId]/detail/page.tsx
  packages/front-end/provider/query-client-provider.tsx
  packages/front-end/schema/backend.schema.ts
  packages/front-end/util/axios.ts
Labels: bug, development

#181 feat: logout page
  packages/front-end/app/dashboard/_components/Sidebar/SidebarUser.tsx
  packages/front-end/app/dashboard/layout.tsx
  packages/front-end/app/logout/page.tsx
Labels: development

#182 refactor: logout function
  packages/front-end/app/logout/page.tsx
Labels: development

#183 Be/175 get session session
  packages/api-server/src/session-files/entities/session-file.entity.ts
  packages/api-server/src/session-files/session-files.service.ts
  packages/api-server/src/sessions/dto/session.response.dto.ts
  packages/api-server/src/sessions/sessions.controller.ts
  packages/api-server/src/sessions/sessions.service.ts
  packages/front-end/schema/backend.schema.ts
Labels: enhancement

#184 feat: session join page
  packages/front-end/app/dashboard/(data)/_components/OptionHeader.tsx
  packages/front-end/app/dashboard/(data)/layout.tsx
  packages/front-end/app/dashboard/(data)/session/create/page.tsx
  packages/front-end/app/dashboard/(data)/session/host/_components/SessionHeader.tsx
  packages/front-end/app/dashboard/(data)/session/join/page.tsx
  packages/front-end/app/dashboard/(data)/session/participant/_components/SessionHeader.tsx
  packages/front-end/app/dashboard/_components/Sidebar/index.tsx
  packages/front-end/app/dashboard/layout.tsx
  packages/front-end/components/Button.tsx
  packages/front-end/components/LineEdit.tsx
Labels: development

#188 fix: session.response.dto fileList type
  packages/api-server/src/sessions/dto/session.response.dto.ts
  packages/front-end/schema/backend.schema.ts
Labels: fix

#186 185 session detail
  packages/front-end/app/sessions/[sessionId]/detail/_components/HostSession/DriveFileUpload.tsx
  packages/front-end/app/sessions/[sessionId]/detail/_components/HostSession/FileUploadModal.tsx
  packages/front-end/app/sessions/[sessionId]/detail/_components/HostSession/LocalFileUpload.tsx
  packages/front-end/app/sessions/[sessionId]/detail/_components/HostSession/index.tsx
  packages/front-end/app/sessions/[sessionId]/detail/page.tsx
  packages/front-end/components/ModalContainer.tsx
  packages/front-end/mocks/handlers.ts
  packages/front-end/package.json
  yarn.lock
Labels: development

#191 fix: Change Redirect url
  packages/api-server/src/auth/auth.controller.ts
Labels: fix

#195 fix: Remove Logout redirect url
  packages/api-server/src/auth/auth.controller.ts
Labels: fix

#205 Be/200 auth logic change
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/cookie.option.ts
  packages/api-server/src/auth/strateties/jwt.strategy.ts
  packages/api-server/src/auth/strateties/refresh.strategy.ts
  packages/api-server/src/main.ts
  packages/front-end/util/axios.ts
Labels: enhancement, fix

#206 203 drive header
  packages/front-end/app/files/_components/FileHeader.tsx
  packages/front-end/app/files/_components/FileTable.tsx
  packages/front-end/app/files/_components/FileUploadModal.tsx
  packages/front-end/app/files/_components/LocalFileUpload.tsx
  packages/front-end/app/files/page.tsx
  packages/front-end/app/sessions/detail/[sessionId]/_components/HostSession/DriveFileUpload.tsx
  packages/front-end/app/sessions/detail/[sessionId]/_components/HostSession/FileUploadModal.tsx
  packages/front-end/app/sessions/detail/[sessionId]/_components/HostSession/LocalFileUpload.tsx
  packages/front-end/app/sessions/detail/[sessionId]/_components/HostSession/index.tsx
  packages/front-end/app/sessions/detail/[sessionId]/_components/ParticipantSession/index.tsx
  packages/front-end/app/sessions/detail/[sessionId]/error.tsx
  packages/front-end/app/sessions/detail/[sessionId]/page.tsx
  packages/front-end/app/sessions/participant/_components/SessionTable.tsx
  packages/front-end/util/axios.ts
Labels: development

#199 feat: setup blank pages
  packages/front-end/app/_components/Sidebar/SidebarLink.tsx
  packages/front-end/app/_components/Sidebar/SidebarUser.tsx
  packages/front-end/app/dashboard/page.tsx
  packages/front-end/app/files/page.tsx
  packages/front-end/app/help/page.tsx
  packages/front-end/app/page.tsx
  packages/front-end/app/sessions/create/page.tsx
  packages/front-end/app/sessions/join/page.tsx
  packages/front-end/app/settings/_components/UserInfoEdit.tsx
  packages/front-end/app/settings/_components/UserModal.tsx
  packages/front-end/app/settings/_components/UserModalTop.tsx
  packages/front-end/app/settings/page.tsx
Labels: development

#211 fix: router structure
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarBaseElement.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarDirectory.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarGroup.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarLink.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarUser.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/index.tsx
  packages/front-end/app/(sidebar-pages)/dashboard/page.tsx
  packages/front-end/app/(sidebar-pages)/files/_components/FileHeader.tsx
  packages/front-end/app/(sidebar-pages)/files/_components/FileTable.tsx
  packages/front-end/app/(sidebar-pages)/files/_components/FileUploadModal.tsx
  packages/front-end/app/(sidebar-pages)/files/_components/LocalFileUpload.tsx
  packages/front-end/app/(sidebar-pages)/files/page.tsx
  packages/front-end/app/(sidebar-pages)/layout.tsx
  packages/front-end/app/(sidebar-pages)/sessions/create/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/DriveFileUpload.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/FileUploadModal.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/LocalFileUpload.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/index.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/ParticipantSession/index.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/error.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/SessionHeader.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/SessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/join/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/SessionHeader.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/SessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/page.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserInfoEdit.tsx
  packages/front-end/app/(sidebar-pages)/settings/page.tsx
  packages/front-end/app/layout.tsx
Labels: fix

#212 fix: import
  packages/front-end/app/(sidebar-pages)/settings/page.tsx
Labels: fix

#213 fix: api call with valid role query param
  packages/front-end/app/(sidebar-pages)/layout.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/SessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/SessionTable.tsx
  packages/front-end/util/getRoleFromURL.tsx
  yarn.lock
Labels: bug

#214 feat: account settings page
  packages/front-end/app/(sidebar-pages)/settings/_components/UserInfoEdit.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserProfileEdit.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserProfileSettings.tsx
  packages/front-end/app/(sidebar-pages)/settings/page.tsx
Labels: development

#222 Be/189 socket
  .idea/vcs.xml
  package-lock.json
  package.json
  packages/.DS_Store
  packages/socket-server/.eslintrc.js
  packages/socket-server/.gitignore
  packages/socket-server/.prettierrc
  packages/socket-server/README.md
  packages/socket-server/nest-cli.json
  packages/socket-server/package.json
  packages/socket-server/src/app.controller.spec.ts
  packages/socket-server/src/app.controller.ts
  packages/socket-server/src/app.module.ts
  packages/socket-server/src/app.service.ts
  packages/socket-server/src/auth/auth.module.ts
  packages/socket-server/src/auth/jwt.payload.ts
  packages/socket-server/src/auth/ws.guard.ts
  packages/socket-server/src/exception/all-exception.filter.ts
  packages/socket-server/src/main.ts
  packages/socket-server/src/socket/dto/create-socket.dto.ts
  packages/socket-server/src/socket/dto/update-socket.dto.ts
  packages/socket-server/src/socket/entities/socket.entity.ts
  packages/socket-server/src/socket/socket.gateway.spec.ts
  packages/socket-server/src/socket/socket.gateway.ts
  packages/socket-server/src/socket/socket.module.ts
  packages/socket-server/src/socket/socket.service.spec.ts
  packages/socket-server/src/socket/socket.service.ts
  packages/socket-server/test/app.e2e-spec.ts
  packages/socket-server/test/jest-e2e.json
  packages/socket-server/tsconfig.build.json
  packages/socket-server/tsconfig.json
  yarn.lock
Labels: development

#217 216 session create
  packages/api-server/src/sessions/dto/create-session.dto.ts
  packages/front-end/app/(sidebar-pages)/sessions/create/_components/SessionCreateForm.tsx
  packages/front-end/app/(sidebar-pages)/sessions/create/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/LocalFileUpload.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/index.tsx
  packages/front-end/client/FileSelectAtom.tsx
  packages/front-end/components/FileUploadAndSelectModal/DriveFileUpload.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/schema/backend.schema.ts
Labels: development

#231 fix: dependency
  packages/api-server/src/sessions/sessions.module.ts
Labels: fix

#232 Be/227 patch user profile fix
  packages/api-server/src/users/dto/update-user-profile.dto.ts
  packages/api-server/src/users/dto/update-user.dto.ts
  packages/api-server/src/users/users.controller.ts
  packages/api-server/src/users/users.module.ts
Labels: enhancement

#233 225 file upload
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/components/LocalFIleUpload.tsx
Labels: bug, development

#235 refactor: remove duplicate components / fix typos
  packages/front-end/.eslintrc.json
  packages/front-end/app/(sidebar-pages)/sessions/create/_components/SessionCreateForm.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/index.tsx
  packages/front-end/components/FileUploadAndSelectModal/DriveFileUpload.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/components/FileUploader.tsx
  packages/front-end/components/LocalFIleUpload.tsx
Labels: enhancement

#238 Fix swagger-typescript-api bug
  packages/api-server/package.json
  packages/front-end/schema/backend.schema.ts
  yarn.lock
Labels: bug

#241 feat: /file api
  packages/front-end/components/FileUploader.tsx
Labels: development
