Repository Uni-class/catch-up-repo, pull requests merged in 2024-10, with the labels that each got.

#432 431 profile validate
  packages/front-end/app/(sidebar-pages)/sessions/join/page.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserProfileSettings.tsx
  packages/front-end/components/ProfileImage.tsx
Labels: bug, enhancement

#435 434 chase host page
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainter.tsx
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainterControlBar.tsx
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainterControlBarButton.tsx
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterController.ts
  packages/front-end/PaintPDF/components/PDFPainter/types/index.ts
  packages/front-end/app/view/[sessionId]/_components/HostViewer.tsx
  packages/front-end/app/view/[sessionId]/_components/Mode.tsx
  packages/front-end/app/view/[sessionId]/_components/ParticipantViewer.tsx
  packages/front-end/app/view/[sessionId]/_hooks/useEnsureVisibleWhileDraw.ts
  packages/front-end/app/view/[sessionId]/_hooks/useParticipantSocket.ts
  packages/front-end/panda.config.ts
Labels: enhancement

#439 fix: Get Sessions after Session deleted
  packages/api-server/src/users/users.service.ts
Labels: bug

#440 aBe/fix got session by code
  packages/api-server/src/sessions/sessions.controller.ts
  packages/api-server/src/sessions/sessions.service.ts
Labels: bug

#441 423 session delay
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainterControlBar.tsx
  packages/front-end/app/(sidebar-pages)/sessions/create/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/index.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/ParticipantSession/index.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/HostSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/join/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/ParticipantSessionTable.tsx
  packages/front-end/app/view/_components/HostViewer.tsx
  packages/front-end/app/view/_components/Mode.tsx
  packages/front-end/app/view/_components/ParticipantViewer.tsx
  packages/front-end/app/view/_components/PreviewPages.tsx
  packages/front-end/app/view/_hooks/useBatchSocket.ts
  packages/front-end/app/view/_hooks/useEnsureVisibleWhileDraw.ts
  packages/front-end/app/view/_hooks/useHostSocket.ts
  packages/front-end/app/view/_hooks/useParticipantSocket.ts
  packages/front-end/app/view/_hooks/useReceiveDrawCache.ts
  packages/front-end/app/view/_types/ViewerType.ts
  packages/front-end/app/view/_utils/differentialRecord.ts
  packages/front-end/app/view/_utils/integralRecord.ts
  packages/front-end/app/view/error.tsx
  packages/front-end/app/view/loading.tsx
  packages/front-end/app/view/page.tsx
  packages/front-end/hook/useRouter.tsx
Labels: enhancement

#442 fix: page blink
  packages/front-end/PaintPDF/components/PDF/BasePDFRenderer.tsx
  packages/front-end/PaintPDF/components/PDF/hooks/usePDFViewerController.ts
Labels: bug

#447 Note api
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterController.ts
  packages/front-end/PaintPDF/components/PDFPainter/utils/indexedDBUtils.ts
  packages/front-end/app/view/_components/HostViewer.tsx
  packages/front-end/app/view/_components/ParticipantViewer.tsx
  packages/front-end/app/view/_hooks/usePostDraw.ts
  packages/front-end/package.json
  yarn.lock
Labels: development

#452 Be/451 get session host note
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/auth.service.ts
  packages/api-server/src/users/users.controller.ts
  packages/api-server/src/users/users.service.ts
Labels: development

#443 feat: create placeholder components
  packages/front-end/app/_components/NavBar/NavBar.tsx
  packages/front-end/components/Placeholder/Placeholder.tsx
  packages/front-end/components/Placeholder/PlaceholderLayout.tsx
  packages/front-end/panda.config.ts
Labels: development

#460 fix: note schema options
  packages/api-server/src/users/schemas/note.schema.ts
Labels: bug

#453 450 download
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainterControlBar.tsx
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainterControlBarButton.tsx
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterController.ts
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterInstanceController.ts
  packages/front-end/PaintPDF/components/PDFPainter/types/index.ts
  packages/front-end/app/view/_components/Download.tsx
  packages/front-end/app/view/_components/HostViewer.tsx
  packages/front-end/app/view/_components/Mode.tsx
  packages/front-end/app/view/_components/ParticipantViewer.tsx
  packages/front-end/app/view/_hooks/usePostDraw.ts
  packages/front-end/app/view/_utils/downloadUtils/apiUtils.ts
  packages/front-end/app/view/_utils/downloadUtils/convertUtils.ts
  packages/front-end/app/view/_utils/downloadUtils/downloadUtils.ts
  packages/front-end/app/view/_utils/downloadUtils/drawUtils.ts
  packages/front-end/app/view/_utils/downloadUtils/getMergedPDFBytes.ts
  packages/front-end/app/view/_utils/downloadUtils/pdfUtils.ts
  packages/front-end/package.json
  yarn.lock
Labels: development

#454 feat: open external links on new tab
  packages/front-end/PaintPDF/components/PDF/BasePDFRenderer.tsx
  packages/front-end/PaintPDF/components/PDF/hooks/usePDFViewerController.ts
  packages/front-end/styled-system/types/prop-type.d.ts
Labels: enhancement

#459 feat: pdf loading skeleton ui
  packages/front-end/app/view/_components/PreviewPages.tsx
  packages/front-end/components/Placeholder/Placeholder.tsx
  packages/front-end/components/Placeholder/PlaceholderLayout.tsx
Labels: development

#456 feat: add auto save
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterController.ts
  packages/front-end/PaintPDF/components/PDFPainter/types/index.ts
Labels: enhancement

#463 fix: create session
  packages/api-server/src/sessions/sessions.controller.ts
  packages/api-server/src/sessions/sessions.service.ts
  packages/api-server/src/users/users.service.ts
Labels: bug

#464 fix: placeholder ui components
  packages/front-end/components/Placeholder/PlaceholderLayout.tsx
Labels: fix

#467 Main page UI
  packages/front-end/app/_components/AdditionalFeature/Hero.tsx
  packages/front-end/app/_components/AdditionalFeature/RoleProfile.tsx
  packages/front-end/app/_components/AdditionalFeature/index.tsx
  packages/front-end/app/_components/Banner.tsx
  packages/front-end/app/_components/Feature.tsx
  packages/front-end/app/_components/Footer/Footer.tsx
  packages/front-end/app/_components/Footer/FooterGroup.tsx
  packages/front-end/app/_components/Footer/FooterItem.tsx
  packages/front-end/app/_components/NavBar/NavBar.tsx
  packages/front-end/app/_components/NavBar/NavBarItem.tsx
  packages/front-end/app/_components/NavBar/Profile.tsx
  packages/front-end/app/_components/Recommend/RecommendCard.tsx
  packages/front-end/app/_components/Recommend/index.tsx
  packages/front-end/app/layout.tsx
  packages/front-end/app/page.tsx
  packages/front-end/public/banner-image.png
  packages/front-end/public/icons/note-download.svg
  packages/front-end/public/icons/recommend-drawer.svg
  packages/front-end/public/icons/recommend-instructor.svg
  packages/front-end/public/icons/recommend-share.svg
  packages/front-end/public/icons/recommend-study.svg
  packages/front-end/public/icons/share.svg
  packages/front-end/public/image/role-instructor.png
  packages/front-end/public/image/role-student.png
  packages/front-end/public/image/save-feature.png
  packages/front-end/public/logo-horizontal-white.svg
  packages/front-end/public/logo-horizontal.svg
  packages/front-end/style/theme.ts
  packages/front-end/styled-system/tokens/index.mjs
  packages/front-end/styled-system/tokens/tokens.d.ts
  packages/front-end/styled-system/types/prop-type.d.ts
Labels: development

#466 Be/465 multer utf8
  package.json
  packages/api-server/src/files/files.controller.ts
  packages/api-server/src/files/files.service.ts
  yarn.lock
Labels: enhancement, fix

#471 feat: login color change
  packages/front-end/app/login/page.tsx
Labels: enhancement

#474 472 sidebar
  packages/front-end/app/(sidebar-pages)/_components/Header/HeaderAccuont.tsx
  packages/front-end/app/(sidebar-pages)/_components/Header/index.tsx
  packages/front-end/app/(sidebar-pages)/_components/NavTitle/index.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarGroup.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarLink.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/TopLogo.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/index.tsx
  packages/front-end/app/(sidebar-pages)/layout.tsx
  packages/front-end/app/_components/Banner.tsx
  packages/front-end/app/layout.tsx
  packages/front-end/app/login/page.tsx
  packages/front-end/app/page.tsx
  packages/front-end/const/routeTitle.ts
  packages/front-end/public/icons/route-arrow.svg
  packages/front-end/style/theme.ts
  packages/front-end/styled-system/tokens/index.mjs
  packages/front-end/styled-system/tokens/tokens.d.ts
  packages/front-end/styled-system/types/prop-type.d.ts
  packages/front-end/type/PropTypes/LinkPropType.ts
Labels: development

#476 feat: link button home
  packages/front-end/app/_components/Banner.tsx
Labels: enhancement

#479 469 system
  .gitignore
  packages/front-end/.gitignore
  packages/front-end/.storybook/main.ts
  packages/front-end/app/(sidebar-pages)/_components/Header/HeaderAccuont.tsx
  packages/front-end/app/(sidebar-pages)/_components/NavTitle/index.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarGroup.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarLink.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/index.tsx
  packages/front-end/app/(sidebar-pages)/layout.tsx
  packages/front-end/app/_components/AdditionalFeature/RoleProfile.tsx
  packages/front-end/app/_components/Banner.tsx
  packages/front-end/app/_components/Feature.tsx
  packages/front-end/app/_components/Footer/Footer.tsx
  packages/front-end/app/_components/Footer/FooterGroup.tsx
  packages/front-end/app/_components/Footer/FooterItem.tsx
  packages/front-end/app/_components/NavBar/NavBar.tsx
  packages/front-end/app/_components/NavBar/Profile.tsx
  packages/front-end/app/_components/Recommend/RecommendCard.tsx
  packages/front-end/app/login/page.tsx
  packages/front-end/app/page.tsx
  packages/front-end/app/view/_components/Common/Header/HeaderControlButton.tsx
  packages/front-end/app/view/_components/Common/Header/index.tsx
  packages/front-end/app/view/_components/Host/HostViewer.tsx
  packages/front-end/components/Button.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/components/FileUploader/FileUploadModal.tsx
  packages/front-end/components/Label.tsx
  packages/front-end/components/LineEdit.tsx
  packages/front-end/package.json
  packages/front-end/panda.config.ts
  packages/front-end/public/icons/settings.svg
  packages/front-end/stories/Button.stories.tsx
  packages/front-end/stories/LineEdit.stories.tsx
  packages/front-end/style/theme.ts
  packages/front-end/styled-system/tokens/index.mjs
  packages/front-end/styled-system/tokens/tokens.d.ts
  packages/front-end/styled-system/types/prop-type.d.ts
  yarn.lock
Labels: enhancement, development

#484 feat: color palette visualize
  packages/front-end/stories/Color.stories.tsx
  packages/front-end/stories/ColorPalette.tsx
Labels: development

#488 487 table
  packages/front-end/app/(sidebar-pages)/files/_components/FileTable.tsx
  packages/front-end/app/(sidebar-pages)/files/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/_components/SessionFormTemplate.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/ParticipantSession/index.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/HostSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/join/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/ParticipantSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/page.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserProfileSettings.tsx
  packages/front-end/app/help/page.tsx
  packages/front-end/app/view/_components/Common/CodeOverlay.tsx
  packages/front-end/app/view/_components/Common/Download.tsx
  packages/front-end/app/view/_components/Host/HostViewer.tsx
  packages/front-end/app/view/_components/Participant/ParticipantViewer.tsx
  packages/front-end/components/Button/Button.tsx
  packages/front-end/components/Button/LinkButton.tsx
  packages/front-end/components/Checkbox.tsx
  packages/front-end/components/FileUploadAndSelectModal/DriveFileSelect.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/components/FileUploader/FileUploadModal.tsx
  packages/front-end/components/FileUploader/FileUploadPreview.tsx
  packages/front-end/components/FileUploader/FileUploader.tsx
  packages/front-end/components/SelectableTable.tsx
  packages/front-end/components/Table.tsx
  packages/front-end/components/Text.tsx
  packages/front-end/public/icons/delete.svg
  packages/front-end/public/icons/join-regacy.svg
  packages/front-end/public/icons/join.svg
  packages/front-end/public/icons/upload.svg
  packages/front-end/stories/Button.stories.tsx
  packages/front-end/stories/LinkButton.stories.tsx
Labels: development

#486 477 dashboard
  packages/front-end/app/(sidebar-pages)/_components/NavTitle/index.tsx
  packages/front-end/app/(sidebar-pages)/dashboard/loading.tsx
  packages/front-end/app/(sidebar-pages)/dashboard/page.tsx
  packages/front-end/app/(sidebar-pages)/layout.tsx
  packages/front-end/app/view/error.tsx
  packages/front-end/hook/useLoginRedirectWithContext.ts
  packages/front-end/hook/useLoginRedirectWithError.ts
Labels: development

#496 feat: style panel
  packages/front-end/PaintPDF/components/Painter/Painter.css
  packages/front-end/PaintPDF/components/Painter/Painter.tsx
Labels: enhancement
