Repository Uni-class/catch-up-repo, pull requests merged in 2024-08, with the labels that each got.

#247 Be/245 file name encoding
  packages/api-server/src/files/files.controller.ts
  packages/api-server/src/files/files.service.ts
  packages/front-end/schema/backend.schema.ts
Labels: enhancement

#250 fix: files to file
  packages/api-server/src/files/files.controller.ts
Labels: bug

#253 fix: FileName encoding to NFC
  packages/api-server/src/files/files.service.ts
Labels: bug

#249 244 view session
  packages/front-end/app/view/[sessionId]/_components/PDFViewer.tsx
  packages/front-end/app/view/[sessionId]/_util/pdfWorkerPolyfill.ts
  packages/front-end/app/view/[sessionId]/page.tsx
  packages/front-end/components/FileUploadAndSelectModal/DriveFileSelect.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/next.config.mjs
  packages/front-end/package.json
  yarn.lock
Labels: development

#254 252 file delete
  packages/front-end/app/(sidebar-pages)/files/_components/FileTable.tsx
  packages/front-end/components/FileUploader.tsx
Labels: development

#264 Be/262 user profile fix
  packages/api-server/src/users/dto/create-user.dto.ts
  packages/api-server/src/users/users.controller.ts
Labels: fix

#260 feat: GET user/profile at sidebar
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarUser.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/index.tsx
Labels: development

#266 236 refactor file upload modal
  packages/.DS_Store
  packages/front-end/app/(sidebar-pages)/files/_components/FileTable.tsx
  packages/front-end/app/(sidebar-pages)/files/_components/FileUploadModal.tsx
  packages/front-end/app/(sidebar-pages)/files/_fetcher/FileTableFetcher.tsx
  packages/front-end/app/(sidebar-pages)/sessions/create/_components/SessionCreateForm.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/index.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/HostSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_fetcher/HostSessionTableFetcher.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/ParticipantSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_fetcher/ParticipantSessionTableFetcher.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserProfileSettings.tsx
  packages/front-end/app/logout/page.tsx
  packages/front-end/components/Button.tsx
  packages/front-end/components/Checkbox.tsx
  packages/front-end/components/FileUploadAndSelectModal/DriveFileSelect.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/components/FileUploader.tsx
  packages/front-end/components/FileUploader/FileUploadPreview.tsx
  packages/front-end/components/FileUploader/FileUploader.tsx
  packages/front-end/components/LineEdit.tsx
  packages/front-end/components/LinkButton.tsx
  packages/front-end/components/ModalContainer.tsx
  packages/front-end/public/icons/close.svg
  packages/front-end/public/icons/document.svg
  packages/front-end/public/icons/pdf.svg
  packages/front-end/public/icons/plus.svg
  packages/front-end/public/icons/repeat.svg
  packages/front-end/util/getIsChecked.ts
  packages/front-end/utils/axios.ts
  packages/front-end/utils/formatByteSize.ts
Labels: enhancement, development, fix

#277 275 aws ecs connect
  .github/workflows/api-server-deploy.yml
  .github/workflows/front-end-deploy.yml
  .github/workflows/socket-server-deploy.yml
  aws/api-server-td.json
  packages/api-server/.dockerignore
  packages/api-server/Dockerfile
Labels: development

#279 273 fix file uploader
  packages/front-end/app/(sidebar-pages)/files/_components/FileTable.tsx
  packages/front-end/app/(sidebar-pages)/files/_components/FileUploadModal.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/HostSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/ParticipantSessionTable.tsx
  packages/front-end/app/viewer/[fileId]/page.tsx
  packages/front-end/components/FileUploader/FileUploader.tsx
  packages/front-end/components/ModalContainer.tsx
  packages/front-end/components/SelectableTable.tsx
  packages/front-end/hook/useRouter.tsx
Labels: enhancement, fix

#280 278 build fix
  packages/front-end/app/(sidebar-pages)/files/_components/FileUploadModal.tsx
  packages/front-end/app/logout/page.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/components/ModalContainer.tsx
  packages/front-end/next.config.mjs
  packages/front-end/package.json
Labels: bug

#282 281 pdf worker
  packages/front-end/.gitignore
  packages/front-end/app/view/[sessionId]/_components/PDFViewer.tsx
  packages/front-end/app/view/[sessionId]/_util/pdfWorkerPolyfill.ts
  packages/front-end/app/view/[sessionId]/page.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/components/ModalContainer.tsx
Labels: bug

#285 fix: error part delete
  packages/front-end/schema/backend.schema.ts
Labels: bug

#292 feat: Return Not null file data
  packages/api-server/src/sessions/sessions.service.ts
Labels: enhancement

#286 fix: 282 pr
  packages/front-end/components/ModalContainer.tsx
Labels: fix

#293 feat: logout error handle
  packages/front-end/app/logout/page.tsx
Labels: development

#294 289 load actual document
  package.json
  packages/front-end/app/view/[sessionId]/_components/PDFViewer.tsx
  packages/front-end/app/view/[sessionId]/_util/pdfWorkerPolyfill.ts
  packages/front-end/app/view/[sessionId]/page.tsx
  packages/front-end/app/viewer/[fileId]/page.tsx
  packages/front-end/components/DocumentViewer/PDF/PDFViewer.tsx
  yarn.lock
Labels: enhancement, development

#298 296 remove msw
  packages/front-end/app/(sidebar-pages)/layout.tsx
  packages/front-end/components/DocumentViewer/PDF/PDFViewer.tsx
  packages/front-end/mocks/browser.ts
  packages/front-end/mocks/data/sessions.ts
  packages/front-end/mocks/handlers.ts
  packages/front-end/mocks/handlers/user.ts
  packages/front-end/package.json
  packages/front-end/provider/index.tsx
  packages/front-end/provider/msw-provider.tsx
  packages/front-end/public/mockServiceWorker.js
  yarn.lock
Labels: bug

#301 300 goto view
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/index.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/ParticipantSession/index.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/loading.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/HostSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/ParticipantSessionTable.tsx
  packages/front-end/app/view/[sessionId]/page.tsx
  packages/front-end/components/LinkButton.tsx
Labels: development

#302 300 goto view
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/HostSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/ParticipantSessionTable.tsx
  packages/front-end/components/LinkButton.tsx
Labels: bug, enhancement

#303 283 tldraw
  packages/front-end/app/globals.css
  packages/front-end/app/view/[sessionId]/page.tsx
  packages/front-end/components/DocumentViewer/PDF/PDFViewer.tsx
  packages/front-end/package.json
  yarn.lock
Labels: development

#304 fix: Dockerfile optimization
  packages/api-server/Dockerfile
  packages/front-end/Dockerfile
  packages/socket-server/Dockerfile
Labels: enhancement

#307 305 build error
  packages/front-end/app/view/[sessionId]/page.tsx
  packages/front-end/app/viewer/[fileId]/page.tsx
  packages/front-end/components/DocumentViewer/PDF/PDFViewer.tsx
  packages/front-end/utils/pdfWorkerPolyfill.ts
Labels: bug

#315 feat: /user/session/:sessionId/join update
  packages/api-server/src/users/users.controller.ts
Labels: enhancement

#310 feat: build-test workflow
  .github/workflows/build-test.yml
  .yarnrc.yml
  yarn.lock
Labels: development

#313 312 join
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/ParticipantSession/index.tsx
  packages/front-end/app/view/[sessionId]/_components/HostViewer.tsx
  packages/front-end/app/view/[sessionId]/_components/ParticipantViewer.tsx
  packages/front-end/app/view/[sessionId]/error.tsx
  packages/front-end/app/view/[sessionId]/page.tsx
  packages/front-end/next.config.mjs
Labels: development

#322 feat: onSendMessage 추가
  packages/socket-server/src/socket/socket.gateway.ts
Labels: enhancement

#324 chore: socket-server build test work flow
  .github/workflows/build-test.yml
Labels: enhancement

#326 325 socket event
  .github/workflows/build-test.yml
  packages/api-server/src/auth/cookie.option.ts
  packages/front-end/app/view/[sessionId]/_hooks/useHostSocket.ts
  packages/front-end/app/view/[sessionId]/_hooks/useParticipantSocket.ts
  packages/socket-server/src/socket/socket.gateway.ts
Labels: enhancement, development

#328 chore: add packages for socket server
  packages/socket-server/package.json
  yarn.lock
Labels: bug

#330 chore: remove if condition
  .github/workflows/build-test.yml
Labels: bug

#335 feat: CreateUserSessionFile
  packages/api-server/src/users/users.service.ts
Labels: enhancement

#333 Be/332 socket userid and host
  packages/socket-server/src/socket/socket.gateway.ts
  packages/socket-server/src/socket/socket.service.ts
Labels: enhancement

#336 feat: useSetResize custom hook
  packages/front-end/components/DocumentViewer/ hooks/useSetSize.ts
  packages/front-end/components/DocumentViewer/PDF/PDFViewer.tsx
Labels: bug, development

#350 fix: don't render East Asian text in legacy pdf file
  packages/front-end/components/DocumentViewer/PDF/PDFViewer.tsx
Labels: bug

#352 316 default profile
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/SidebarUser.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserProfileEdit.tsx
  packages/front-end/components/ProfileImage.tsx
  packages/front-end/public/profile-default.jpg
Labels: development

#339 Append userSession check logic
  packages/api-server/src/users/users.service.ts
Labels: enhancement, fix

#345 feat: Cookie Option change
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/cookie.option.ts
Labels: enhancement

#351 Be/348 mongodb connection test
  packages/api-server/package.json
  packages/api-server/src/app.module.ts
  packages/api-server/src/sessions/sessions.module.ts
  packages/api-server/src/users/schemas/note.schema.ts
  packages/api-server/src/users/users.controller.ts
  packages/api-server/src/users/users.module.ts
  packages/api-server/src/users/users.service.ts
  yarn.lock
Labels: enhancement, development

#343 fix: socket connection
  packages/socket-server/src/socket/socket.gateway.ts
Labels: fix

#347 Be/364 socket user session check
  packages/socket-server/src/socket/socket.gateway.ts
  packages/socket-server/src/socket/socket.service.ts
Labels: enhancement, development

#355 fix: Invalid character in path
  packages/front-end/components/DocumentViewer/PDF/PDFViewer.tsx
  packages/front-end/components/DocumentViewer/hooks/useSetSize.ts
Labels: fix

#358 356 session api
  packages/api-server/src/sessions/sessions.controller.ts
  packages/front-end/app/(sidebar-pages)/_components/RedirectToLogin.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/page.tsx
  packages/front-end/app/view/[sessionId]/_components/HostViewer.tsx
  packages/front-end/app/view/[sessionId]/_components/ParticipantViewer.tsx
  packages/front-end/app/view/[sessionId]/page.tsx
Labels: bug, enhancement

#364 fix: getRefreshTokenFromHeader
  packages/api-server/src/auth/auth.service.ts
Labels: bug

#361 Be/360 session code fix
  packages/api-server/src/sessions/sessions.service.ts
Labels: enhancement, fix

#366 362 zip data
  packages/front-end/app/view/[sessionId]/_components/HostViewer.tsx
  packages/front-end/app/view/[sessionId]/_components/ParticipantViewer.tsx
  packages/front-end/app/view/[sessionId]/_hooks/useHostSocket.ts
  packages/front-end/app/view/[sessionId]/_hooks/useParticipantSocket.ts
  packages/front-end/app/view/[sessionId]/_utils/diffrentialRecord.ts
  packages/front-end/app/view/[sessionId]/_utils/integralRecord.ts
  packages/front-end/app/view/[sessionId]/page.tsx
  packages/socket-server/src/main.ts
  packages/socket-server/src/socket/socket.gateway.ts
Labels: development
