Repository Uni-class/catch-up-repo, pull requests merged in 2024-09, with the labels that each got.

#372 B3/371 redis adapter
  .github/workflows/socket-server-deploy.yml
  packages/socket-server/package.json
  packages/socket-server/src/main.ts
  packages/socket-server/src/redis-io.adapter.ts
  packages/socket-server/src/socket/socket.gateway.ts
  yarn.lock
Labels: development

#377 375 paintpdf
  packages/front-end/PaintPDF/assets/data/snapshot.json
  packages/front-end/PaintPDF/assets/examples/test.pdf
  packages/front-end/PaintPDF/assets/examples/test2.pdf
  packages/front-end/PaintPDF/assets/icons/arrow-left.svg
  packages/front-end/PaintPDF/assets/icons/arrow-right.svg
  packages/front-end/PaintPDF/assets/icons/tool-edit.svg
  packages/front-end/PaintPDF/assets/icons/tool-hand.svg
  packages/front-end/PaintPDF/assets/icons/tool-pointer.svg
  packages/front-end/PaintPDF/components/PDF/BasePDFRenderer.tsx
  packages/front-end/PaintPDF/components/PDF/PDFRenderer.css
  packages/front-end/PaintPDF/components/PDF/PDFRenderer.tsx
  packages/front-end/PaintPDF/components/PDF/PDFViewer.tsx
  packages/front-end/PaintPDF/components/PDF/hooks/usePDFViewerController.ts
  packages/front-end/PaintPDF/components/PDF/index.ts
  packages/front-end/PaintPDF/components/PDF/types/index.ts
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainter.tsx
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainterControlBar.tsx
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainterControlBarButton.tsx
  packages/front-end/PaintPDF/components/PDFPainter/PainterInstance.tsx
  packages/front-end/PaintPDF/components/PDFPainter/PainterInstanceGenerator.tsx
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterController.ts
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterInstanceController.ts
  packages/front-end/PaintPDF/components/PDFPainter/index.ts
  packages/front-end/PaintPDF/components/PDFPainter/types/index.ts
  packages/front-end/PaintPDF/components/Painter/Painter.css
  packages/front-end/PaintPDF/components/Painter/Painter.tsx
  packages/front-end/PaintPDF/components/Painter/index.ts
  packages/front-end/PaintPDF/components/Painter/types/index.ts
  packages/front-end/PaintPDF/components/index.ts
  packages/front-end/app/view/[sessionId]/_components/HostViewer.tsx
  packages/front-end/app/view/[sessionId]/_components/ParticipantViewer.tsx
Labels: development

#388 385 account info control
  packages/front-end/app/(sidebar-pages)/_components/RedirectToLogin.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/AccountOptionsViewer.tsx
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/index.tsx
  packages/front-end/app/(sidebar-pages)/layout.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserProfileEdit.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserProfileSettings.tsx
  packages/front-end/hook/useAccount.tsx
  packages/front-end/provider/index.tsx
Labels: enhancement

#393 fix: load editor snapshot with mergeRemoteChanges
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterController.ts
  packages/front-end/app/view/[sessionId]/_hooks/useReceiveDrawCache.ts
Labels: bug

#400 feat: fix sidebar layout
  packages/front-end/app/(sidebar-pages)/_components/Sidebar/AccountOptionsViewer.tsx
  packages/front-end/app/(sidebar-pages)/layout.tsx
  packages/front-end/app/(sidebar-pages)/sessions/create/_components/SessionCreateForm.tsx
  packages/front-end/app/(sidebar-pages)/sessions/join/page.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserProfileSettings.tsx
  packages/front-end/components/LineEdit.tsx
  packages/front-end/panda.config.ts
  packages/front-end/styled-system/css/conditions.mjs
  packages/front-end/styled-system/jsx/is-valid-prop.mjs
  packages/front-end/styled-system/types/conditions.d.ts
Labels: enhancement

#404 Be/395 socket data change
  packages/socket-server/package.json
  packages/socket-server/src/exception/ws-exception.filter.ts
  packages/socket-server/src/socket/socket.gateway.ts
  yarn.lock
Labels: enhancement

#408 407 page info
  packages/front-end/app/view/[sessionId]/_components/HostViewer.tsx
  packages/front-end/app/view/[sessionId]/_components/ParticipantViewer.tsx
  packages/front-end/app/view/[sessionId]/_hooks/useBatchSocket.ts
  packages/front-end/app/view/[sessionId]/_hooks/useHostSocket.ts
  packages/front-end/app/view/[sessionId]/_hooks/useParticipantSocket.ts
Labels: enhancement

#409 fix: init user and set rooms
  packages/front-end/app/view/[sessionId]/_hooks/useHostSocket.ts
  packages/front-end/app/view/[sessionId]/_hooks/useParticipantSocket.ts
Labels: bug

#410 Be/394 socket reinitialize
  packages/front-end/.dockerignore
  packages/socket-server/.dockerignore
  packages/socket-server/src/socket/socket.gateway.ts
Labels: enhancement

#412 fix: first come, init user
  packages/front-end/app/view/[sessionId]/_hooks/useHostSocket.ts
  packages/front-end/app/view/[sessionId]/_hooks/useParticipantSocket.ts
Labels: bug

#413 refactor: sendPageNumber divide
  packages/socket-server/src/socket/socket.gateway.ts
Labels: enhancement

#414 feat: page number
  packages/front-end/app/view/[sessionId]/_hooks/useHostSocket.ts
  packages/front-end/app/view/[sessionId]/_hooks/useParticipantSocket.ts
Labels: development

#419 Be/418 cookie secure option
  packages/api-server/src/auth/cookie.option.ts
  packages/socket-server/src/socket/socket.service.ts
Labels: bug, enhancement

#422 Cookie Domain
  .github/workflows/api-server-deploy.yml
  packages/api-server/src/auth/cookie.option.ts
  packages/socket-server/src/socket/socket.service.ts
Labels: bug

#402 fix: file upload select modals
  packages/front-end/app/(sidebar-pages)/files/_components/FileTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/create/_components/SessionCreateForm.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/index.tsx
  packages/front-end/components/FileUploadAndSelectModal/DriveFileSelect.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/components/FileUploader/FileUploadModal.tsx
  packages/front-end/components/FileUploader/FileUploader.tsx
  packages/front-end/components/ModalContainer.tsx
Labels: enhancement, fix

#405 Session create form
  packages/front-end/app/(sidebar-pages)/sessions/_components/SessionFormTemplate.tsx
  packages/front-end/app/(sidebar-pages)/sessions/create/_components/SessionCreateForm.tsx
  packages/front-end/app/(sidebar-pages)/sessions/create/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/_components/HostSession/index.tsx
  packages/front-end/components/FileUploadAndSelectModal/DriveFileSelect.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
  packages/front-end/hook/useFormData.ts
  packages/front-end/package.json
  packages/front-end/provider/query-client-provider.tsx
  packages/front-end/type/SessionFormType.ts
  yarn.lock
Labels: enhancement

#428 feat: landing page
  packages/front-end/app/_components/Carousel/index.tsx
  packages/front-end/app/_components/Footer/Footer.tsx
  packages/front-end/app/_components/Footer/FooterGroup.tsx
  packages/front-end/app/_components/Footer/FooterItem.tsx
  packages/front-end/app/_components/NavBar/NavBar.tsx
  packages/front-end/app/_components/NavBar/NavBarItem.tsx
  packages/front-end/app/layout.tsx
  packages/front-end/app/page.tsx
  packages/front-end/app/privacy-policy/page.css
  packages/front-end/app/privacy-policy/page.tsx
  packages/front-end/public/logo-variant.svg
Labels: development

#430 feat: session form error
  packages/front-end/app/(sidebar-pages)/sessions/_components/SessionFormTemplate.tsx
Labels: enhancement
