Repository Uni-class/catch-up-repo, pull requests merged in 2024-11, with the labels that each got.

#502 Responsive home
  packages/front-end/app/_components/AdditionalFeature/Hero.tsx
  packages/front-end/app/_components/Banner.tsx
  packages/front-end/app/_components/Footer/Footer.tsx
  packages/front-end/app/_components/NavBar/Profile.tsx
  packages/front-end/app/page.tsx
Labels: enhancement

#507 Be/503 pagination
  packages/api-server/src/user-sessions/entities/user-session.entity.ts
  packages/api-server/src/users/dto/get-files-query.dto.ts
  packages/api-server/src/users/dto/get-files-response.dto.ts
  packages/api-server/src/users/dto/get-sessions-response.dto.ts
  packages/api-server/src/users/types/get-sessions-query.type.ts
  packages/api-server/src/users/types/role.type.ts
  packages/api-server/src/users/users.controller.ts
  packages/api-server/src/users/users.service.ts
  packages/front-end/schema/backend.schema.ts
Labels: enhancement

#509 fix: main page relative style
  packages/front-end/app/_components/Feature.tsx
  packages/front-end/app/page.tsx
Labels: enhancement

#508 feat: table pagination
  packages/front-end/app/(sidebar-pages)/_components/Header/index.tsx
  packages/front-end/app/(sidebar-pages)/dashboard/page.tsx
  packages/front-end/app/(sidebar-pages)/files/_components/FileTable.tsx
  packages/front-end/app/(sidebar-pages)/files/_fetcher/FileTableFetcher.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/HostSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/_fetcher/HostSessionTableFetcher.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/page.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/ParticipantSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_fetcher/ParticipantSessionTableFetcher.tsx
  packages/front-end/app/_components/Carousel/index.tsx
  packages/front-end/app/view/_components/Common/Header/index.tsx
  packages/front-end/app/view/page.tsx
  packages/front-end/components/Button/Button.tsx
  packages/front-end/components/Button/LinkButton.tsx
  packages/front-end/components/FileUploadAndSelectModal/DriveFileSelect.tsx
  packages/front-end/components/SelectableTable.tsx
  packages/front-end/public/icons/arrow-left-end.svg
  packages/front-end/public/icons/arrow-left.svg
  packages/front-end/public/icons/arrow-right-end.svg
  packages/front-end/public/icons/arrow-right.svg
Labels: development

#512 511 event handler
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterController.ts
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterEventHandler.ts
  packages/front-end/PaintPDF/components/PDFPainter/types/index.ts
Labels: development

#516 515 zoom
  packages/front-end/app/view/_components/Common/PDFFooter/PageIndexChange.tsx
  packages/front-end/app/view/_components/Common/PDFFooter/PageIndexShow.tsx
  packages/front-end/app/view/_components/Common/PDFFooter/PageZoomControl.tsx
  packages/front-end/app/view/_components/Common/PDFFooter/index.tsx
  packages/front-end/app/view/_components/Common/PageControl/index.tsx
  packages/front-end/app/view/_components/Host/HostViewer.tsx
  packages/front-end/app/view/_components/Participant/ParticipantViewer.tsx
  packages/front-end/public/icons/minus.svg
  packages/front-end/public/icons/plus.svg
Labels: development

#519 Modal unmount
  packages/front-end/app/(sidebar-pages)/sessions/_components/SessionFormTemplate.tsx
  packages/front-end/components/FileUploadAndSelectModal/DriveFileSelect.tsx
  packages/front-end/components/FileUploadAndSelectModal/index.tsx
Labels: bug

#521 chore: install and build after change directory to each worksapce
  .github/workflows/build-test.yml
  packages/front-end/app/view/_hooks/usePostDraw.ts
Labels: bug

#529 Be/524 redirect if login fail
  packages/api-server/src/auth/guards/googleauth.guard.ts
  packages/api-server/src/auth/guards/kakaoauth.guard.ts
  packages/api-server/src/auth/guards/naverauth.guard.ts
  packages/api-server/src/auth/strateties/google.strategy.ts
  packages/api-server/src/auth/strateties/kakao.strategy.ts
  packages/api-server/src/auth/strateties/naver.strategy.ts
Labels: enhancement

#532 Fix profile settings
  packages/front-end/app/(sidebar-pages)/sessions/host/_components/HostSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/_components/ParticipantSessionTable.tsx
  packages/front-end/app/(sidebar-pages)/settings/_components/UserProfileSettings.tsx
  packages/front-end/components/Button/Button.tsx
Labels: fix

#527 refactor: logout feedback
  packages/front-end/app/logout/page.tsx
Labels: enhancement

#539 Be/533 guest login
  packages/api-server/src/auth/auth.controller.ts
  packages/api-server/src/auth/auth.service.ts
  packages/api-server/src/auth/dto/guest-body.dto.ts
  packages/api-server/src/auth/jwt.payload.ts
  packages/api-server/src/users/user.converter.ts
Labels: enhancement, development

#537 535 loading UI
  packages/front-end/app/(sidebar-pages)/dashboard/loading.tsx
  packages/front-end/app/(sidebar-pages)/sessions/detail/[sessionId]/loading.tsx
  packages/front-end/app/(sidebar-pages)/sessions/host/loading.tsx
  packages/front-end/app/(sidebar-pages)/sessions/join/loading.tsx
  packages/front-end/app/(sidebar-pages)/sessions/participant/loading.tsx
  packages/front-end/app/(sidebar-pages)/settings/page.tsx
  packages/front-end/app/help/loading.tsx
  packages/front-end/app/login/loading.tsx
  packages/front-end/app/logout/loading.tsx
  packages/front-end/app/view/loading.tsx
Labels: enhancement

#547 Session join UI
  packages/front-end/app/(sidebar-pages)/sessions/join/_components/ModalContainer.tsx
  packages/front-end/app/(sidebar-pages)/sessions/join/_components/SessionInfo.tsx
  packages/front-end/app/(sidebar-pages)/sessions/join/page.tsx
Labels: development

#545 540 prettier
  .github/workflows/build-test.yml
  packages/front-end/.prettierignore
  packages/front-end/.prettierrc
  packages/front-end/package.json
  yarn.lock
Labels: enhancement

#551 542 viewer refactor
  packages/front-end/PaintPDF/components/PDF/PDFViewer.tsx
  packages/front-end/PaintPDF/components/PDF/hooks/usePDFViewerController.ts
  packages/front-end/PaintPDF/components/PDF/types/index.ts
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainter.tsx
  packages/front-end/PaintPDF/components/PDFPainter/PDFPainterControlBar.tsx
  packages/front-end/PaintPDF/components/PDFPainter/PainterInstance.tsx
  packages/front-end/PaintPDF/components/PDFPainter/hooks/usePDFPainterController.ts
  packages/front-end/PaintPDF/components/PDFPainter/types/index.ts
  packages/front-end/PaintPDF/components/Painter/Painter.tsx
  packages/front-end/app/view/_components/Common/Header/ColorPicker.tsx
  packages/front-end/app/view/_components/Common/Header/HeaderToolTipButton.tsx
  packages/front-end/app/view/_components/Common/Header/ToolButton.tsx
  packages/front-end/app/view/_components/Common/Header/ToolPanel.tsx
  packages/front-end/app/view/_components/Common/Header/index.tsx
  packages/front-end/app/view/_components/Common/PDFFooter/PageZoomControl.tsx
  packages/front-end/app/view/_components/Common/PreviewPages.tsx
  packages/front-end/app/view/_hooks/useParticipantSocket.ts
  packages/front-end/components/Divider.tsx
  packages/front-end/public/icons/brush.svg
  packages/front-end/public/icons/eraser.svg
  packages/front-end/public/icons/move.svg
  packages/front-end/public/icons/pen.svg
  packages/front-end/public/icons/pointer.svg
  packages/front-end/public/icons/redo.svg
  packages/front-end/public/icons/region-select.svg
  packages/front-end/public/icons/type.svg
  packages/front-end/public/icons/undo.svg
  packages/front-end/public/icons/view.svg
  packages/front-end/public/icons/zoom.svg
Labels: enhancement, fix
